// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#ifndef _KNOMI2_UI_H
#define _KNOMI2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_ScreenMainGif
void ui_ScreenMainGif_screen_init(void);
void ui_event_ScreenMainGif(lv_event_t * e);
extern lv_obj_t * ui_ScreenMainGif;
// SCREEN: ui_ScreenWelcome
void ui_ScreenWelcome_screen_init(void);
extern lv_obj_t * ui_ScreenWelcome;
extern lv_obj_t * ui_label_welcome;
// SCREEN: ui_ScreenWIFIConnecting
void ui_ScreenWIFIConnecting_screen_init(void);
extern lv_obj_t * ui_ScreenWIFIConnecting;
extern lv_obj_t * ui_spinner_wifi_connecting;
extern lv_obj_t * ui_Image7;
// SCREEN: ui_ScreenWIFIDisconnect
void ui_ScreenWIFIDisconnect_screen_init(void);
extern lv_obj_t * ui_ScreenWIFIDisconnect;
extern lv_obj_t * ui_img_wifi_disconnect;
extern lv_obj_t * ui_label_wifi_disconnect;
// SCREEN: ui_ScreenExtrude
void ui_ScreenExtrude_screen_init(void);
void ui_event_ScreenExtrude(lv_event_t * e);
extern lv_obj_t * ui_ScreenExtrude;
void ui_event_btn_extruder_extrude(lv_event_t * e);
extern lv_obj_t * ui_btn_extruder_extrude;
extern lv_obj_t * ui_label_extruder_extrude;
void ui_event_btn_extruder_retract(lv_event_t * e);
extern lv_obj_t * ui_btn_extruder_retract;
extern lv_obj_t * ui_label_extruder_retract;
void ui_event_btn_extruder_temp(lv_event_t * e);
extern lv_obj_t * ui_btn_extruder_temp;
extern lv_obj_t * ui_img_extruder_nozzle;
extern lv_obj_t * ui_label_extruder_target;
extern lv_obj_t * ui_label_extruder_actual;
void ui_event_btn_extruder_speed(lv_event_t * e);
extern lv_obj_t * ui_btn_extruder_speed;
extern lv_obj_t * ui_label_extruder_length;
extern lv_obj_t * ui_label_extruder_speed;
// SCREEN: ui_ScreenMove
void ui_ScreenMove_screen_init(void);
void ui_event_ScreenMove(lv_event_t * e);
extern lv_obj_t * ui_ScreenMove;
void ui_event_btn_move_abl(lv_event_t * e);
extern lv_obj_t * ui_btn_move_abl;
extern lv_obj_t * ui_img_move_abl;
void ui_event_btn_move_qgl(lv_event_t * e);
extern lv_obj_t * ui_btn_move_qgl;
extern lv_obj_t * ui_img_move_qgl;
void ui_event_btn_move_home(lv_event_t * e);
extern lv_obj_t * ui_btn_move_home;
extern lv_obj_t * ui_img_move_home;
extern lv_obj_t * ui_label_move_abl;
extern lv_obj_t * ui_label_move_qgl;
extern lv_obj_t * ui_label_move_home;
// SCREEN: ui_ScreenTemp
void ui_ScreenTemp_screen_init(void);
void ui_event_ScreenTemp(lv_event_t * e);
extern lv_obj_t * ui_ScreenTemp;
void ui_event_btn_temp_nozzle(lv_event_t * e);
extern lv_obj_t * ui_btn_temp_nozzle;
extern lv_obj_t * ui_img_temp_nozzle;
extern lv_obj_t * ui_label_temp_nozzle_target;
extern lv_obj_t * ui_label_temp_nozzle_actual;
void ui_event_btn_temp_bed(lv_event_t * e);
extern lv_obj_t * ui_btn_temp_bed;
extern lv_obj_t * ui_img_temp_bed;
extern lv_obj_t * ui_label_temp_bed_target;
extern lv_obj_t * ui_label_temp_bed_actual;
void ui_event_btn_temp_preheat(lv_event_t * e);
extern lv_obj_t * ui_btn_temp_preheat;
extern lv_obj_t * ui_label_temp_preheat;
// SCREEN: ui_ScreenSetTemp
void ui_ScreenSetTemp_screen_init(void);
void ui_event_ScreenSetTemp(lv_event_t * e);
extern lv_obj_t * ui_ScreenSetTemp;
extern lv_obj_t * ui_img_set_temp_dial;
void ui_event_btn_set_temp_ok(lv_event_t * e);
extern lv_obj_t * ui_btn_set_temp_ok;
extern lv_obj_t * ui_img_set_temp_ok;
extern lv_obj_t * ui_set_temp_target;
// SCREEN: ui_ScreenSetExtrude
void ui_ScreenSetExtrude_screen_init(void);
void ui_event_ScreenSetExtrude(lv_event_t * e);
extern lv_obj_t * ui_ScreenSetExtrude;
extern lv_obj_t * ui_roller_set_extrude_length;
extern lv_obj_t * ui_roller_set_extrude_speed;
void ui_event_btn_set_extrude_ok(lv_event_t * e);
extern lv_obj_t * ui_btn_set_extrude_ok;
extern lv_obj_t * ui_img_set_extrude_ok;
// SCREEN: ui_ScreenPrinting
void ui_ScreenPrinting_screen_init(void);
void ui_event_ScreenPrinting(lv_event_t * e);
extern lv_obj_t * ui_ScreenPrinting;
extern lv_obj_t * ui_label_printing_progress;
extern lv_obj_t * ui_arc_printing_progress;
extern lv_obj_t * ui_slider_printing_acc_x;
extern lv_obj_t * ui_label_printing_acc_x;
extern lv_obj_t * ui_slider_printing_acc_y;
extern lv_obj_t * ui_label_printing_acc_y;
extern lv_obj_t * ui_slider_printing_acc_z;
extern lv_obj_t * ui_label_printing_acc_z;
extern lv_obj_t * ui_arc_bg_1;
extern lv_obj_t * ui_arc_bg_2_1;
extern lv_obj_t * ui_arc_bg_2_2;
extern lv_obj_t * ui_arc_bg_2_3;
// SCREEN: ui_ScreenHeatingNozzle
void ui_ScreenHeatingNozzle_screen_init(void);
extern lv_obj_t * ui_ScreenHeatingNozzle;
extern lv_obj_t * ui_slider_heating_nozzle;
extern lv_obj_t * ui_label_heating_nozzle_target;
extern lv_obj_t * ui_label_heating_nozzle_actual;
// SCREEN: ui_ScreenHeatingBed
void ui_ScreenHeatingBed_screen_init(void);
extern lv_obj_t * ui_ScreenHeatingBed;
extern lv_obj_t * ui_slider_heating_bed;
extern lv_obj_t * ui_label_heating_bed_target;
extern lv_obj_t * ui_label_heating_bed_actual;
// SCREEN: ui_ScreenRoller
void ui_ScreenRoller_screen_init(void);
void ui_event_ScreenRoller(lv_event_t * e);
extern lv_obj_t * ui_ScreenRoller;
extern lv_obj_t * ui_roller;
void ui_event_btn_roller(lv_event_t * e);
extern lv_obj_t * ui_btn_roller;
extern lv_obj_t * ui_img_roller_right;
extern lv_obj_t * ui_img_roller_left;
// SCREEN: ui_ScreenQRCode
void ui_ScreenQRCode_screen_init(void);
void ui_event_ScreenQRCode(lv_event_t * e);
extern lv_obj_t * ui_ScreenQRCode;
extern lv_obj_t * ui_label_qr_code;
// SCREEN: ui_ScreenBacklight
void ui_ScreenBacklight_screen_init(void);
void ui_event_ScreenBacklight(lv_event_t * e);
extern lv_obj_t * ui_ScreenBacklight;
void ui_event_slider_backlight(lv_event_t * e);
extern lv_obj_t * ui_slider_backlight;
extern lv_obj_t * ui_img_backlight;
// SCREEN: ui_ScreenDialog
void ui_ScreenDialog_screen_init(void);
void ui_event_ScreenDialog(lv_event_t * e);
extern lv_obj_t * ui_ScreenDialog;
void ui_event_btn_dialog_cancel(lv_event_t * e);
extern lv_obj_t * ui_btn_dialog_cancel;
void ui_event_btn_dialog_ok(lv_event_t * e);
extern lv_obj_t * ui_btn_dialog_ok;
extern lv_obj_t * ui_img_dialog_ok;
extern lv_obj_t * ui_label_dialog;
// SCREEN: ui_ScreenPopup
void ui_ScreenPopup_screen_init(void);
extern lv_obj_t * ui_ScreenPopup;
extern lv_obj_t * ui_img_popup;
extern lv_obj_t * ui_textarea_popup;
void ui_event_btn_popup_ok(lv_event_t * e);
extern lv_obj_t * ui_btn_popup_ok;
extern lv_obj_t * ui_img_popup_ok;
// SCREEN: ui_ScreenColorWheel
void ui_ScreenColorWheel_screen_init(void);
extern lv_obj_t * ui_ScreenColorWheel;
void ui_event_theme_color_wheel(lv_event_t * e);
extern lv_obj_t * ui_theme_color_wheel;
void ui_event_btn_color_wheel_ok(lv_event_t * e);
extern lv_obj_t * ui_btn_color_wheel_ok;
extern lv_obj_t * ui_img_color_wheel_ok;
// SCREEN: ui_ScreenInfo
void ui_ScreenInfo_screen_init(void);
void ui_event_ScreenInfo(lv_event_t * e);
extern lv_obj_t * ui_ScreenInfo;
extern lv_obj_t * ui_img_left_sta_ip;
extern lv_obj_t * ui_img_mid_sta_ip;
extern lv_obj_t * ui_label_sta_ip_name;
extern lv_obj_t * ui_label_sta_ip;
extern lv_obj_t * ui_img_right_sta_ip;
extern lv_obj_t * ui_img_mid_ap_ip;
extern lv_obj_t * ui_label_ap_ip_name;
extern lv_obj_t * ui_label_ap_ip;
extern lv_obj_t * ui_img_left_ap_ip;
extern lv_obj_t * ui_img_right_ap_ip;
extern lv_obj_t * ui_img_left_local;
extern lv_obj_t * ui_img_mid_local;
extern lv_obj_t * ui_label_local_name;
extern lv_obj_t * ui_label_local;
extern lv_obj_t * ui_img_right_local;
extern lv_obj_t * ui_img_left_host;
extern lv_obj_t * ui_img_mid_host;
extern lv_obj_t * ui_label_host_name;
extern lv_obj_t * ui_label_host;
extern lv_obj_t * ui_img_right_host;
// SCREEN: ui_ScreenTestImg
void ui_ScreenTestImg_screen_init(void);
void ui_event_ScreenTestImg(lv_event_t * e);
extern lv_obj_t * ui_ScreenTestImg;
extern lv_obj_t * ui_img_test;
// SCREEN: ui_ScreenTestSensor
void ui_ScreenTestSensor_screen_init(void);
void ui_event_ScreenTestSensor(lv_event_t * e);
extern lv_obj_t * ui_ScreenTestSensor;
extern lv_obj_t * ui_label_test_x_name;
extern lv_obj_t * ui_label_test_y_name;
extern lv_obj_t * ui_label_test_z_name;
extern lv_obj_t * ui_label_test_x;
extern lv_obj_t * ui_label_test_y;
extern lv_obj_t * ui_label_test_z;
void ui_event_btn_test_wifi(lv_event_t * e);
extern lv_obj_t * ui_btn_test_wifi;
extern lv_obj_t * ui_label_test_wifi;
extern lv_obj_t * ui_label_ssid1_name;
extern lv_obj_t * ui_label_ssid_2_name;
extern lv_obj_t * ui_label_ssid3_name;
extern lv_obj_t * ui_label_ssid1;
extern lv_obj_t * ui_label_ssid2;
extern lv_obj_t * ui_label_ssid3;
extern lv_obj_t * ui_slider_acc_x;
extern lv_obj_t * ui_slider_acc_y;
extern lv_obj_t * ui_slider_acc_z;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_logo_png);    // assets\logo.png
LV_IMG_DECLARE(ui_img_wifi_disconnect_png);    // assets\wifi_disconnect.png
LV_IMG_DECLARE(ui_img_bg_png);    // assets\bg.png
LV_IMG_DECLARE(ui_img_btn_rec_png);    // assets\btn_rec.png
LV_IMG_DECLARE(ui_img_sta_temp_png);    // assets\sta_temp.png
LV_IMG_DECLARE(ui_img_nozzle_png);    // assets\nozzle.png
LV_IMG_DECLARE(ui_img_sta_extrude_png);    // assets\sta_extrude.png
LV_IMG_DECLARE(ui_img_btn_move_png);    // assets\btn_move.png
LV_IMG_DECLARE(ui_img_abl_png);    // assets\abl.png
LV_IMG_DECLARE(ui_img_qgl_png);    // assets\qgl.png
LV_IMG_DECLARE(ui_img_home_png);    // assets\home.png
LV_IMG_DECLARE(ui_img_bed_png);    // assets\bed.png
LV_IMG_DECLARE(ui_img_dial_png);    // assets\dial.png
LV_IMG_DECLARE(ui_img_btn_dialog_png);    // assets\btn_dialog.png
LV_IMG_DECLARE(ui_img_img_ok_png);    // assets\img_ok.png
LV_IMG_DECLARE(ui_img_acc_png);    // assets\acc.png
LV_IMG_DECLARE(ui_img_nozzle_gray_png);    // assets\nozzle_gray.png
LV_IMG_DECLARE(ui_img_nozzle_red_png);    // assets\nozzle_red.png
LV_IMG_DECLARE(ui_img_bed_gray_png);    // assets\bed_gray.png
LV_IMG_DECLARE(ui_img_bed_red_png);    // assets\bed_red.png
LV_IMG_DECLARE(ui_img_roller_rec_mid_png);    // assets\roller_rec_mid.png
LV_IMG_DECLARE(ui_img_roller_rec_right_png);    // assets\roller_rec_right.png
LV_IMG_DECLARE(ui_img_roller_rec_left_png);    // assets\roller_rec_left.png
LV_IMG_DECLARE(ui_img_slider_backlight_png);    // assets\slider_backlight.png
LV_IMG_DECLARE(ui_img_backlight_png);    // assets\backlight.png
LV_IMG_DECLARE(ui_img_btn_cancel_png);    // assets\btn_cancel.png
LV_IMG_DECLARE(ui_img_popup_png);    // assets\popup.png
LV_IMG_DECLARE(ui_img_test_png);    // assets\test.png

LV_FONT_DECLARE(ui_font_InterSeimiBold32);
LV_FONT_DECLARE(ui_font_InterSemiBold14);
LV_FONT_DECLARE(ui_font_InterSemiBold16);
LV_FONT_DECLARE(ui_font_InterSemiBold18);
LV_FONT_DECLARE(ui_font_InterSemiBold20);
LV_FONT_DECLARE(ui_font_InterSemiBold24);
LV_FONT_DECLARE(ui_font_InterSemiBold48);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
