// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void lv_roller_set_type_print(lv_event_t * e);
void lv_btn_extruder_extrude(lv_event_t * e);
void lv_btn_extruder_retract(lv_event_t * e);
void lv_temp_set_type_nozzle(lv_event_t * e);
void lv_dialog_goto_abl(lv_event_t * e);
void lv_dialog_goto_qgl(lv_event_t * e);
void lv_dialog_goto_home(lv_event_t * e);
void lv_roller_set_type_settings(lv_event_t * e);
void lv_temp_set_type_bed(lv_event_t * e);
void lv_roller_set_type_preheat(lv_event_t * e);
void lv_set_temp_back_to_previous(lv_event_t * e);
void lv_set_temp_btn_ok(lv_event_t * e);
void lv_btn_set_extrude(lv_event_t * e);
void lv_roller_set_extrude(lv_event_t * e);
void lv_dialog_goto_cancel(lv_event_t * e);
void lv_dialog_goto_pause_resume(lv_event_t * e);
void lv_roller_gesture_left(lv_event_t * e);
void lv_roller_gesture_right(lv_event_t * e);
void lv_roller_btn_clicked(lv_event_t * e);
void lv_tft_set_backlight(lv_event_t * e);
void lv_dialog_back_to_previous_menu(lv_event_t * e);
void lv_dialog_btn_ok(lv_event_t * e);
void ui_event_popup_ok(lv_event_t * e);
void lv_colorwheel_value_change(lv_event_t * e);
void lv_colorwheel_btn_ok(lv_event_t * e);
void lv_test_sensor_btn_ok(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
