// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#ifndef _UI_COMP_LABEL2_H
#define _UI_COMP_LABEL2_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Label2
#define UI_COMP_LABEL2_LABEL2 0
#define _UI_COMP_LABEL2_NUM 1
lv_obj_t * ui_Label2_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
