// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#include "../ui.h"

void ui_ScreenTestSensor_screen_init(void)
{
    ui_ScreenTestSensor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenTestSensor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenTestSensor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenTestSensor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_test_x_name = lv_label_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_label_test_x_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_test_x_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_test_x_name, 60);
    lv_obj_set_y(ui_label_test_x_name, 85);
    lv_label_set_text(ui_label_test_x_name, "X:");
    lv_obj_set_style_text_color(ui_label_test_x_name, lv_color_hex(0xFFD164), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_test_x_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_test_y_name = lv_label_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_label_test_y_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_test_y_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_test_y_name, 100);
    lv_obj_set_y(ui_label_test_y_name, 85);
    lv_label_set_text(ui_label_test_y_name, "Y:");
    lv_obj_set_style_text_color(ui_label_test_y_name, lv_color_hex(0xFFD164), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_test_y_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_test_z_name = lv_label_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_label_test_z_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_test_z_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_test_z_name, 145);
    lv_obj_set_y(ui_label_test_z_name, 85);
    lv_label_set_text(ui_label_test_z_name, "Z:");
    lv_obj_set_style_text_color(ui_label_test_z_name, lv_color_hex(0xFFD164), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_test_z_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_test_x = lv_label_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_label_test_x, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_test_x, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_test_x, 75);
    lv_obj_set_y(ui_label_test_x, 85);
    lv_label_set_text(ui_label_test_x, "");

    ui_label_test_y = lv_label_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_label_test_y, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_test_y, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_test_y, 115);
    lv_obj_set_y(ui_label_test_y, 85);
    lv_label_set_text(ui_label_test_y, "");

    ui_label_test_z = lv_label_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_label_test_z, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_test_z, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_test_z, 160);
    lv_obj_set_y(ui_label_test_z, 85);
    lv_label_set_text(ui_label_test_z, "");

    ui_btn_test_wifi = lv_imgbtn_create(ui_ScreenTestSensor);
    lv_imgbtn_set_src(ui_btn_test_wifi, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_rec_png, NULL);
    lv_obj_set_width(ui_btn_test_wifi, 108);
    lv_obj_set_height(ui_btn_test_wifi, 38);
    lv_obj_set_x(ui_btn_test_wifi, 0);
    lv_obj_set_y(ui_btn_test_wifi, -15);
    lv_obj_set_align(ui_btn_test_wifi, LV_ALIGN_BOTTOM_MID);

    ui_label_test_wifi = lv_label_create(ui_btn_test_wifi);
    lv_obj_set_width(ui_label_test_wifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_test_wifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_test_wifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_test_wifi, "Refresh");

    ui_label_ssid1_name = lv_label_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_label_ssid1_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_ssid1_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_ssid1_name, 15);
    lv_obj_set_y(ui_label_ssid1_name, 110);
    lv_label_set_text(ui_label_ssid1_name, "SSID1:");
    lv_obj_set_style_text_color(ui_label_ssid1_name, lv_color_hex(0xFFD164), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_ssid1_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_ssid_2_name = lv_label_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_label_ssid_2_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_ssid_2_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_ssid_2_name, 15);
    lv_obj_set_y(ui_label_ssid_2_name, 135);
    lv_label_set_text(ui_label_ssid_2_name, "SSID2:");
    lv_obj_set_style_text_color(ui_label_ssid_2_name, lv_color_hex(0xFFD164), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_ssid_2_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_ssid3_name = lv_label_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_label_ssid3_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_ssid3_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_ssid3_name, 15);
    lv_obj_set_y(ui_label_ssid3_name, 160);
    lv_label_set_text(ui_label_ssid3_name, "SSID3:");
    lv_obj_set_style_text_color(ui_label_ssid3_name, lv_color_hex(0xFFD164), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_ssid3_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_ssid1 = lv_label_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_label_ssid1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_ssid1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_ssid1, 65);
    lv_obj_set_y(ui_label_ssid1, 110);
    lv_label_set_text(ui_label_ssid1, "");

    ui_label_ssid2 = lv_label_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_label_ssid2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_ssid2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_ssid2, 65);
    lv_obj_set_y(ui_label_ssid2, 135);
    lv_label_set_text(ui_label_ssid2, "");

    ui_label_ssid3 = lv_label_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_label_ssid3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_ssid3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_ssid3, 65);
    lv_obj_set_y(ui_label_ssid3, 160);
    lv_label_set_text(ui_label_ssid3, "");

    ui_slider_acc_x = lv_slider_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_slider_acc_x, 18);
    lv_obj_set_height(ui_slider_acc_x, 58);
    lv_obj_set_x(ui_slider_acc_x, 70);
    lv_obj_set_y(ui_slider_acc_x, 25);
    lv_obj_clear_flag(ui_slider_acc_x, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_slider_acc_x, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slider_acc_x, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_acc_x, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_slider_acc_x, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slider_acc_x, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_acc_x, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slider_acc_x, &ui_img_acc_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_slider_acc_x, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_acc_x, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_slider_acc_y = lv_slider_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_slider_acc_y, 18);
    lv_obj_set_height(ui_slider_acc_y, 58);
    lv_obj_set_x(ui_slider_acc_y, 0);
    lv_obj_set_y(ui_slider_acc_y, 25);
    lv_obj_set_align(ui_slider_acc_y, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_slider_acc_y, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_slider_acc_y, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slider_acc_y, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_acc_y, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_slider_acc_y, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slider_acc_y, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_acc_y, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slider_acc_y, &ui_img_acc_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_slider_acc_y, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_acc_y, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_slider_acc_z = lv_slider_create(ui_ScreenTestSensor);
    lv_obj_set_width(ui_slider_acc_z, 18);
    lv_obj_set_height(ui_slider_acc_z, 58);
    lv_obj_set_x(ui_slider_acc_z, -70);
    lv_obj_set_y(ui_slider_acc_z, 25);
    lv_obj_set_align(ui_slider_acc_z, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_slider_acc_z, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_slider_acc_z, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slider_acc_z, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_acc_z, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_slider_acc_z, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slider_acc_z, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_acc_z, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slider_acc_z, &ui_img_acc_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_slider_acc_z, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_acc_z, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btn_test_wifi, ui_event_btn_test_wifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenTestSensor, ui_event_ScreenTestSensor, LV_EVENT_ALL, NULL);

}
