// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#include "../ui.h"

void ui_ScreenMove_screen_init(void)
{
    ui_ScreenMove = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMove, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMove, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMove, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScreenMove, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_move_abl = lv_imgbtn_create(ui_ScreenMove);
    lv_imgbtn_set_src(ui_btn_move_abl, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_move_png, NULL);
    lv_obj_set_height(ui_btn_move_abl, 72);
    lv_obj_set_width(ui_btn_move_abl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btn_move_abl, 24);
    lv_obj_set_y(ui_btn_move_abl, 45);
    lv_obj_set_style_bg_img_src(ui_btn_move_abl, &ui_img_btn_move_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_move_abl = lv_img_create(ui_btn_move_abl);
    lv_img_set_src(ui_img_move_abl, &ui_img_abl_png);
    lv_obj_set_width(ui_img_move_abl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_img_move_abl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_img_move_abl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_move_abl, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_move_abl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_move_qgl = lv_imgbtn_create(ui_ScreenMove);
    lv_imgbtn_set_src(ui_btn_move_qgl, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_move_png, NULL);
    lv_obj_set_height(ui_btn_move_qgl, 72);
    lv_obj_set_width(ui_btn_move_qgl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btn_move_qgl, 144);
    lv_obj_set_y(ui_btn_move_qgl, 45);

    ui_img_move_qgl = lv_img_create(ui_btn_move_qgl);
    lv_img_set_src(ui_img_move_qgl, &ui_img_qgl_png);
    lv_obj_set_width(ui_img_move_qgl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_img_move_qgl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_img_move_qgl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_move_qgl, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_move_qgl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_move_home = lv_imgbtn_create(ui_ScreenMove);
    lv_imgbtn_set_src(ui_btn_move_home, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_move_png, NULL);
    lv_obj_set_height(ui_btn_move_home, 72);
    lv_obj_set_width(ui_btn_move_home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btn_move_home, 0);
    lv_obj_set_y(ui_btn_move_home, 134);
    lv_obj_set_align(ui_btn_move_home, LV_ALIGN_TOP_MID);

    ui_img_move_home = lv_img_create(ui_btn_move_home);
    lv_img_set_src(ui_img_move_home, &ui_img_home_png);
    lv_obj_set_width(ui_img_move_home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_img_move_home, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_img_move_home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_move_home, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_move_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label_move_abl = lv_label_create(ui_ScreenMove);
    lv_obj_set_width(ui_label_move_abl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_move_abl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_move_abl, 45);
    lv_obj_set_y(ui_label_move_abl, 121);
    lv_label_set_text(ui_label_move_abl, "ABL\n");
    lv_obj_set_style_text_font(ui_label_move_abl, &ui_font_InterSemiBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_move_qgl = lv_label_create(ui_ScreenMove);
    lv_obj_set_width(ui_label_move_qgl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_move_qgl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_move_qgl, -45);
    lv_obj_set_y(ui_label_move_qgl, 121);
    lv_obj_set_align(ui_label_move_qgl, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_label_move_qgl, "QGL\n");
    lv_obj_set_style_text_font(ui_label_move_qgl, &ui_font_InterSemiBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_move_home = lv_label_create(ui_ScreenMove);
    lv_obj_set_width(ui_label_move_home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_move_home, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_move_home, 0);
    lv_obj_set_y(ui_label_move_home, 8);
    lv_obj_set_align(ui_label_move_home, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_label_move_home, "Home\n");
    lv_obj_set_style_text_font(ui_label_move_home, &ui_font_InterSemiBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btn_move_abl, ui_event_btn_move_abl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn_move_qgl, ui_event_btn_move_qgl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn_move_home, ui_event_btn_move_home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenMove, ui_event_ScreenMove, LV_EVENT_ALL, NULL);

}
