// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#include "../ui.h"

void ui_ScreenTestImg_screen_init(void)
{
    ui_ScreenTestImg = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenTestImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenTestImg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenTestImg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_test = lv_img_create(ui_ScreenTestImg);
    lv_img_set_src(ui_img_test, &ui_img_test_png);
    lv_obj_set_width(ui_img_test, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_img_test, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_img_test, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_test, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_test, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ScreenTestImg, ui_event_ScreenTestImg, LV_EVENT_ALL, NULL);

}
