// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#include "../ui.h"

void ui_ScreenBacklight_screen_init(void)
{
    ui_ScreenBacklight = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenBacklight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenBacklight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenBacklight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slider_backlight = lv_slider_create(ui_ScreenBacklight);
    lv_slider_set_range(ui_slider_backlight, 1, 16);
    lv_slider_set_value(ui_slider_backlight, 16, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_slider_backlight) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_slider_backlight, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_slider_backlight, 78);
    lv_obj_set_height(ui_slider_backlight, 134);
    lv_obj_set_x(ui_slider_backlight, 1);
    lv_obj_set_y(ui_slider_backlight, -2);
    lv_obj_set_align(ui_slider_backlight, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_slider_backlight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slider_backlight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_backlight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_slider_backlight, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slider_backlight, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_backlight, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slider_backlight, &ui_img_slider_backlight_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_slider_backlight, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_backlight, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_img_backlight = lv_img_create(ui_ScreenBacklight);
    lv_img_set_src(ui_img_backlight, &ui_img_backlight_png);
    lv_obj_set_width(ui_img_backlight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_img_backlight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_img_backlight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_backlight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_backlight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_slider_backlight, ui_event_slider_backlight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenBacklight, ui_event_ScreenBacklight, LV_EVENT_ALL, NULL);

}
