// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#include "../ui.h"

void ui_ScreenColorWheel_screen_init(void)
{
    ui_ScreenColorWheel = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenColorWheel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenColorWheel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenColorWheel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_theme_color_wheel = lv_colorwheel_create(ui_ScreenColorWheel, true);
    lv_obj_set_width(ui_theme_color_wheel, 220);
    lv_obj_set_height(ui_theme_color_wheel, 220);
    lv_obj_set_align(ui_theme_color_wheel, LV_ALIGN_CENTER);
    lv_obj_set_style_arc_width(ui_theme_color_wheel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_theme_color_wheel, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_theme_color_wheel, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_theme_color_wheel, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_theme_color_wheel, 10, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_btn_color_wheel_ok = lv_imgbtn_create(ui_ScreenColorWheel);
    lv_imgbtn_set_src(ui_btn_color_wheel_ok, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_dialog_png, NULL);
    lv_obj_set_width(ui_btn_color_wheel_ok, 56);
    lv_obj_set_height(ui_btn_color_wheel_ok, 56);
    lv_obj_set_align(ui_btn_color_wheel_ok, LV_ALIGN_CENTER);

    ui_img_color_wheel_ok = lv_img_create(ui_btn_color_wheel_ok);
    lv_img_set_src(ui_img_color_wheel_ok, &ui_img_img_ok_png);
    lv_obj_set_width(ui_img_color_wheel_ok, 24);
    lv_obj_set_height(ui_img_color_wheel_ok, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_align(ui_img_color_wheel_ok, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_color_wheel_ok, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_color_wheel_ok, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_theme_color_wheel, ui_event_theme_color_wheel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn_color_wheel_ok, ui_event_btn_color_wheel_ok, LV_EVENT_ALL, NULL);

}
