// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#include "../ui.h"

void ui_ScreenSetExtrude_screen_init(void)
{
    ui_ScreenSetExtrude = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSetExtrude, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSetExtrude, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSetExtrude, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roller_set_extrude_length = lv_roller_create(ui_ScreenSetExtrude);
    lv_obj_set_width(ui_roller_set_extrude_length, 108);
    lv_obj_set_height(ui_roller_set_extrude_length, 120);
    lv_obj_set_x(ui_roller_set_extrude_length, 2);
    lv_obj_set_y(ui_roller_set_extrude_length, 0);
    lv_obj_set_align(ui_roller_set_extrude_length, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_text_color(ui_roller_set_extrude_length, lv_color_hex(0x7F7F7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_roller_set_extrude_length, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_roller_set_extrude_length, &ui_font_InterSemiBold16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_roller_set_extrude_length, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roller_set_extrude_length, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_roller_set_extrude_length, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_roller_set_extrude_length, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_roller_set_extrude_length, &ui_font_InterSemiBold20, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_roller_set_extrude_length, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roller_set_extrude_length, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_roller_set_extrude_length, &ui_img_btn_rec_png, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_roller_set_extrude_speed = lv_roller_create(ui_ScreenSetExtrude);
    lv_obj_set_width(ui_roller_set_extrude_speed, 108);
    lv_obj_set_height(ui_roller_set_extrude_speed, 120);
    lv_obj_set_x(ui_roller_set_extrude_speed, -2);
    lv_obj_set_y(ui_roller_set_extrude_speed, 0);
    lv_obj_set_align(ui_roller_set_extrude_speed, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_text_color(ui_roller_set_extrude_speed, lv_color_hex(0x7F7F7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_roller_set_extrude_speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_roller_set_extrude_speed, &ui_font_InterSemiBold16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_roller_set_extrude_speed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roller_set_extrude_speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_roller_set_extrude_speed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_roller_set_extrude_speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_roller_set_extrude_speed, &ui_font_InterSemiBold20, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_roller_set_extrude_speed, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roller_set_extrude_speed, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_roller_set_extrude_speed, &ui_img_btn_rec_png, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_btn_set_extrude_ok = lv_imgbtn_create(ui_ScreenSetExtrude);
    lv_imgbtn_set_src(ui_btn_set_extrude_ok, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_dialog_png, NULL);
    lv_obj_set_width(ui_btn_set_extrude_ok, 56);
    lv_obj_set_height(ui_btn_set_extrude_ok, 56);
    lv_obj_set_x(ui_btn_set_extrude_ok, 0);
    lv_obj_set_y(ui_btn_set_extrude_ok, 170);
    lv_obj_set_align(ui_btn_set_extrude_ok, LV_ALIGN_TOP_MID);

    ui_img_set_extrude_ok = lv_img_create(ui_btn_set_extrude_ok);
    lv_img_set_src(ui_img_set_extrude_ok, &ui_img_img_ok_png);
    lv_obj_set_width(ui_img_set_extrude_ok, 24);
    lv_obj_set_height(ui_img_set_extrude_ok, 17);
    lv_obj_set_align(ui_img_set_extrude_ok, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_set_extrude_ok, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_set_extrude_ok, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_btn_set_extrude_ok, ui_event_btn_set_extrude_ok, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenSetExtrude, ui_event_ScreenSetExtrude, LV_EVENT_ALL, NULL);

}
