// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#include "../ui.h"

void ui_ScreenQRCode_screen_init(void)
{
    ui_ScreenQRCode = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenQRCode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenQRCode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenQRCode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_qr_code = lv_label_create(ui_ScreenQRCode);
    lv_obj_set_width(ui_label_qr_code, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_qr_code, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_qr_code, -3);
    lv_obj_set_y(ui_label_qr_code, -30);
    lv_obj_set_align(ui_label_qr_code, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_label_qr_code, "Online Manual");
    lv_obj_set_style_text_font(ui_label_qr_code, &ui_font_InterSemiBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenQRCode, ui_event_ScreenQRCode, LV_EVENT_ALL, NULL);

}
