// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#include "../ui.h"

void ui_ScreenHeatingNozzle_screen_init(void)
{
    ui_ScreenHeatingNozzle = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenHeatingNozzle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenHeatingNozzle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenHeatingNozzle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slider_heating_nozzle = lv_slider_create(ui_ScreenHeatingNozzle);
    lv_obj_set_width(ui_slider_heating_nozzle, 122);
    lv_obj_set_height(ui_slider_heating_nozzle, 125);
    lv_obj_set_align(ui_slider_heating_nozzle, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_slider_heating_nozzle,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_slider_heating_nozzle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slider_heating_nozzle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_heating_nozzle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slider_heating_nozzle, &ui_img_nozzle_gray_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_slider_heating_nozzle, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_slider_heating_nozzle, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_heating_nozzle, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_slider_heating_nozzle, &ui_img_nozzle_red_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_slider_heating_nozzle, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_heating_nozzle, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_label_heating_nozzle_target = lv_label_create(ui_ScreenHeatingNozzle);
    lv_obj_set_width(ui_label_heating_nozzle_target, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_heating_nozzle_target, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_heating_nozzle_target, 0);
    lv_obj_set_y(ui_label_heating_nozzle_target, -20);
    lv_obj_set_align(ui_label_heating_nozzle_target, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_label_heating_nozzle_target, "0℃");
    lv_obj_set_style_text_font(ui_label_heating_nozzle_target, &ui_font_InterSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_heating_nozzle_actual = lv_label_create(ui_ScreenHeatingNozzle);
    lv_obj_set_width(ui_label_heating_nozzle_actual, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_heating_nozzle_actual, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_heating_nozzle_actual, 0);
    lv_obj_set_y(ui_label_heating_nozzle_actual, 20);
    lv_obj_set_align(ui_label_heating_nozzle_actual, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_label_heating_nozzle_actual, "0℃");
    lv_obj_set_style_text_color(ui_label_heating_nozzle_actual, lv_color_hex(0xFFD164), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_heating_nozzle_actual, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_heating_nozzle_actual, &ui_font_InterSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);

}
