// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#include "../ui.h"

void ui_ScreenSetTemp_screen_init(void)
{
    ui_ScreenSetTemp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSetTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSetTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSetTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_set_temp_dial = lv_img_create(ui_ScreenSetTemp);
    lv_img_set_src(ui_img_set_temp_dial, &ui_img_dial_png);
    lv_obj_set_width(ui_img_set_temp_dial, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_img_set_temp_dial, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_img_set_temp_dial, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_set_temp_dial, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_set_temp_dial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_set_temp_ok = lv_imgbtn_create(ui_ScreenSetTemp);
    lv_imgbtn_set_src(ui_btn_set_temp_ok, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_dialog_png, NULL);
    lv_obj_set_width(ui_btn_set_temp_ok, 56);
    lv_obj_set_height(ui_btn_set_temp_ok, 56);
    lv_obj_set_x(ui_btn_set_temp_ok, 0);
    lv_obj_set_y(ui_btn_set_temp_ok, 128);
    lv_obj_set_align(ui_btn_set_temp_ok, LV_ALIGN_TOP_MID);

    ui_img_set_temp_ok = lv_img_create(ui_btn_set_temp_ok);
    lv_img_set_src(ui_img_set_temp_ok, &ui_img_img_ok_png);
    lv_obj_set_width(ui_img_set_temp_ok, 24);
    lv_obj_set_height(ui_img_set_temp_ok, 17);
    lv_obj_set_align(ui_img_set_temp_ok, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_set_temp_ok, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_set_temp_ok, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_set_temp_target = lv_label_create(ui_ScreenSetTemp);
    lv_obj_set_width(ui_set_temp_target, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_set_temp_target, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_set_temp_target, 0);
    lv_obj_set_y(ui_set_temp_target, 72);
    lv_obj_set_align(ui_set_temp_target, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_set_temp_target, "0℃");
    lv_obj_set_style_text_font(ui_set_temp_target, &ui_font_InterSeimiBold32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btn_set_temp_ok, ui_event_btn_set_temp_ok, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenSetTemp, ui_event_ScreenSetTemp, LV_EVENT_ALL, NULL);

}
