// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#include "../ui.h"

void ui_ScreenRoller_screen_init(void)
{
    ui_ScreenRoller = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenRoller, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roller = lv_roller_create(ui_ScreenRoller);
    lv_obj_set_width(ui_roller, 172);
    lv_obj_set_height(ui_roller, 240);
    lv_obj_set_align(ui_roller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_roller, lv_color_hex(0x7F7F7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_roller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_roller, &ui_font_InterSemiBold16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_roller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_roller, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_roller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_roller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_roller, &ui_font_InterSemiBold20, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_roller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_roller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_roller, &ui_img_roller_rec_mid_png, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_btn_roller = lv_btn_create(ui_ScreenRoller);
    lv_obj_set_width(ui_btn_roller, 194);
    lv_obj_set_height(ui_btn_roller, 38);
    lv_obj_set_align(ui_btn_roller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_roller, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_roller, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btn_roller, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_roller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_img_roller_right = lv_img_create(ui_ScreenRoller);
    lv_img_set_src(ui_img_roller_right, &ui_img_roller_rec_right_png);
    lv_obj_set_width(ui_img_roller_right, 11);
    lv_obj_set_height(ui_img_roller_right, 38);
    lv_obj_set_x(ui_img_roller_right, 91);
    lv_obj_set_y(ui_img_roller_right, 0);
    lv_obj_set_align(ui_img_roller_right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_roller_right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_roller_right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_roller_left = lv_img_create(ui_ScreenRoller);
    lv_img_set_src(ui_img_roller_left, &ui_img_roller_rec_left_png);
    lv_obj_set_width(ui_img_roller_left, 11);
    lv_obj_set_height(ui_img_roller_left, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_x(ui_img_roller_left, -92);
    lv_obj_set_y(ui_img_roller_left, 0);
    lv_obj_set_align(ui_img_roller_left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_roller_left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_roller_left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_btn_roller, ui_event_btn_roller, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenRoller, ui_event_ScreenRoller, LV_EVENT_ALL, NULL);

}
