// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Knomi2

#include "../ui.h"

void ui_ScreenWelcome_screen_init(void)
{
    ui_ScreenWelcome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWelcome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenWelcome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenWelcome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_welcome = lv_label_create(ui_ScreenWelcome);
    lv_obj_set_width(ui_label_welcome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_welcome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_welcome, 0);
    lv_obj_set_y(ui_label_welcome, -40);
    lv_obj_set_align(ui_label_welcome, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_label_welcome,
                      "Please use the wireless network\n   function of your computer or\n        mobile phone to search\n         and connect to KNOMI");
    lv_obj_set_style_text_color(ui_label_welcome, lv_color_hex(0x4082F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_welcome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
